title: Pouyan Soleymanijadidi
url: "https://your-username.github.io"
theme: "minimal-mistakes-jekyll"

author:
  name: "Pouyan Soleymanijadidi"
  avatar: "/assets/Pouyan Jadidi 1.jpg"
  bio: "Your bio here."
  location: "Hüttlingen, Deutschland"
  email: "pouyan.sj01@gmail.com"
